### ISSUE TITLE
Obviously https://blog.codinghorror.com/new-programming-jargon/

### ISSUE THREAD

**Issue by Kritner** [codingblocks/CodingVocabulary#1]
This project should either reference, or depend on: https://blog.codinghorror.com/new-programming-jargon/

**Comment by THEjoezack** [comment]
Yes!

**Comment by THEjoezack** [comment]
How does this sound?

**Comment by THEjoezack** [comment]
https://github.com/codingblocks/CodingVocabulary/

**Comment by Kritner** [comment]
Yessssss
